version: '3.8'

#to run: docker-compose up -d

services:
  # Setup for MYSQL docker image
  db:
    image: mysql:5.7
    container_name: mysql-customerapi
    command: --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./customerapi-mysql:/var/lib/mysql
    ports:
      - "3306:3306"
